package pscglobalsolutions.api.services.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2014-11-17T12:05:24.400+05:30
 * Generated source version: 2.6.16
 * 
 */
@WebServiceClient(name = "PSCAPIWS", 
                  wsdlLocation = "file:WebContent/WEB-INF/pscAPIServices.wsdl",
                  targetNamespace = "http://pscglobalsolutions/API/services/wsdl") 
public class PSCAPIWS extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://pscglobalsolutions/API/services/wsdl", "PSCAPIWS");
    public final static QName PSCSOAPPort = new QName("http://pscglobalsolutions/API/services/wsdl", "PSCSOAPPort");
    static {
        URL url = null;
        try {
            url = new URL("file:WebContent/WEB-INF/pscAPIServices.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PSCAPIWS.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:WebContent/WEB-INF/pscAPIServices.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PSCAPIWS(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PSCAPIWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PSCAPIWS() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns PSCAPIService
     */
    @WebEndpoint(name = "PSCSOAPPort")
    public PSCAPIService getPSCSOAPPort() {
        return super.getPort(PSCSOAPPort, PSCAPIService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PSCAPIService
     */
    @WebEndpoint(name = "PSCSOAPPort")
    public PSCAPIService getPSCSOAPPort(WebServiceFeature... features) {
        return super.getPort(PSCSOAPPort, PSCAPIService.class, features);
    }

}
