
package pscglobalsolutions.api.services.wsdl;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2014-11-17T12:05:24.390+05:30
 * Generated source version: 2.6.16
 * 
 */
 
public class PSCAPIService_PSCSOAPPort_Server{

    protected PSCAPIService_PSCSOAPPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new PSCAPIServiceImpl();
        String address = "http://www.example.org/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new PSCAPIService_PSCSOAPPort_Server();
        System.out.println("Server ready..."); 
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
