package pscglobalsolutions.api.services.wsdl;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import pscapp.services.types.ContactInfo;
import pscapp.services.types.ContactInfoResponse;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2014-11-17T12:05:24.376+05:30
 * Generated source version: 2.6.16
 * 
 */
@WebService(targetNamespace = "http://pscglobalsolutions/API/services/wsdl", name = "PSCAPIService")
@XmlSeeAlso({pscapp.services.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PSCAPIService {

    @WebResult(name = "ContactInfo", targetNamespace = "http://pscApp/services/types", partName = "out")
    @WebMethod(action = "http://pscglobalsolutions/API/services/wsdl#getContacts")
    public ContactInfoResponse getContacts(
        @WebParam(partName = "userInfo", name = "UserInfoRequest", targetNamespace = "http://pscApp/services/types")
        pscapp.services.types.UserInfoRequest userInfo
    );

    @WebResult(name = "UserInfo", targetNamespace = "http://pscApp/services/types", partName = "res")
    @WebMethod(action = "http://pscglobalsolutions/API/services/wsdl#loginViaApp")
    public pscapp.services.types.UserInfo loginViaApp(
        @WebParam(partName = "userInfo2", name = "UserInfoRequest2", targetNamespace = "http://pscApp/services/types")
        pscapp.services.types.UserInfoRequest userInfo2
    );
}
